# Generated by Django 3.1.7 on 2021-03-23 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(help_text='Only mp4 files are allowed', upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4',))])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocontent_uploadvideos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('video',),
                'verbose_name_plural': 'videos',
            },
        ),
    ]
