"""
Django settings for usermodels project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# Messages
from django.contrib.messages import constants as messages
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from django.conf.global_settings import EMAIL_HOST_USER

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'Your secret key'
# SECURITY WARNING: keep the secret key used in production secret!
...
RECAPTCHA_SITE_KEY = '6LeO80UcAAAAAOBL1I2WWcvSQjYvKWK-8WOvHhEX' #your reCAPTCHA SITE key

RECAPTCHA_SECRET_KEY = '6LeO80UcAAAAAE7561eA4iv2h6eHaL8_djI1MOiu' #your reCAPTCHA SECRET key
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
	## List apps before admin for overiding django admin style CSS
	'tinymce',
    'fontawesome_free',
	'blog',
	'users',
	'contacts',
    'gunicorn',
	'imagecontent',
	'videocontent',
	'sorl.thumbnail',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'django.contrib.humanize',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'csblog.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': ['templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
				'contacts.context_processors.key',
				'contacts.insert_form.contactform',
			],
		},
	},
]

WSGI_APPLICATION = 'csblog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


if DEBUG:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.mysql',
			'NAME': 'customblog',
			'USER': 'django',
			'PASSWORD': 'Django76',
			'HOST': '127.0.0.1',
			'PORT': '3306',
		}
	}
else:
	DATABASES = {
		'default': {
			'ENGINE': 'django.db.backends.postgresql_psycopg2',
			'NAME': '',
			'USER': '',
			'PASSWORD': '',
			'HOST': 'localhost',
			'PORT': '',
		}
	}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
	BASE_DIR / "static",
]
# media folder settings
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

MESSAGE_TAGS = {
	messages.ERROR: 'danger',
}

try:
	from .local_settings import *
except ImportError:
	pass

## Enable Custom user model extending AbstractBaserUser
AUTH_USER_MODEL = 'users.NewUser'

## Adding tiny ecitor
# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'
# TINYMCE_COMPRESSOR = False
#
TINYMCE_DEFAULT_CONFIG = {
	'cleanup_on_startup': False,
	'custom_undo_redo_levels': 20,
	'selector': '.tinymce',
    'media_dimensions': False,
	'height': '400',
	'theme': 'silver',
	'force_br_newlines': True,
	'force_p_newlines': False,
	'autosave_ask_before_unload': True,
	'autosave_restore_when_empty': True,
	'forced_root_block': '',
	'convert_urls': False,
	'autosave_interval': '20s',
	'image_dimensions': False,
	'object_resizing': False,
	'browser_spellcheck': True,
	'mobile': {
		'menubar': True
	},
	
	'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
	'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
	# 'toolbar2': '''
    #         visualblocks visualchars |
    #         charmap hr pagebreak nonbreaking anchor |  code |
    #         ''',
	'contextmenu': 'formats | link image',
	'menubar': True,
	'statusbar': True,
	'image_class_list': [
		{'title': 'Responsive', 'value': 'img-fluid'}
	],
}

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'tbhedelund@gmail.com'
EMAIL_HOST_PASSWORD = 'Th170258'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER