# Generated by Django 3.1.7 on 2021-04-19 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagecontent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='feat_img',
            field=models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', upload_to='gallery/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
