# Generated by Django 3.1.7 on 2021-03-24 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feat_img',
            field=models.ImageField(blank=True, help_text='Only jpg/jpeg files are allowed', null=True, upload_to='post_img/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
